Detect whether php4 or php5 is installed
This patch makes a lot of changes to the init script and the
ravencore.httpd.conf files which mainly create the facility
for passing various defines to how the control panel webserver
is started. The main highlight here is whether php4 or php5 is
installed.

diff --git a/ravencore/sbin/ravencore.init b/ravencore/sbin/ravencore.init
--- a/ravencore/sbin/ravencore.init
+++ b/ravencore/sbin/ravencore.init
@@ -19,8 +19,34 @@ export GOT_CONF=1
 # don't need to be restarted by them.
 export INIT_RUNNING=1
 
+# tells us if we found source function library for init scripts. Initilize it to zero
+
+found_init_func=0
+
 # Source function library for init scripts.
-. $INITD/functions
+if [ -f $INITD/functions ]; then
+
+    found_init_func=1
+    . $INITD/functions
+
+else
+
+# declare some of the functions we used from the library we didn't find
+
+    success() {
+
+	echo "[ OK ]"
+	
+    }
+
+    failure() {
+
+	echo "[ FAILED ]"
+	
+    }
+
+fi
+
 
 # This will prevent initlog from swallowing up a pass-phrase prompt if
 # mod_ssl needs a pass-phrase from the user.
@@ -31,9 +57,12 @@ pidfile=${PIDFILE-/var/run/ravencore.httpd.pid}
 lockfile=${LOCKFILE-/var/lock/subsys/ravencore.httpd}
 RETVAL=0
 
-# set $opt to whatever $2 is, only known parameter is "nossl"
+# set $opt to whatever $2 is
+# right now, only parameter is "nossl"
+
 ssl_opt=$2
-# if the var/run/httpd.nossl exists, force opt to be nossl
+
+# if the var/run/httpd.nossl exists, force ssl_opt to be nossl
 if [ -f $RC_ROOT/var/run/httpd.nossl ]; then
     ssl_opt="nossl"
 fi
@@ -46,16 +75,15 @@ start() {
 
 # check to see that mysqld is running....
 
-    if [ -z "$(/sbin/pidof mysqld)" ]; then
+    if [ -z "$(pidof mysqld)" ]; then
 	
 # mysqld isn't running.. attempt to start it
-	$INITD/$mysql_service start
-	
+# don't run this command if the script doesn't exist... to supress the error message
+	if [ -f $INITD/$mysql_service ]; then
+	    $INITD/$mysql_service start
+	fi
+
     fi
-
-# say we're starting up...
-
-    echo -n $"Starting control panel: "
 
 # check to make sure the ravencore.httpd binary is the same as /usr/sbin/httpd
 # among other things
@@ -68,12 +96,16 @@ start() {
 
     if [ $RETVAL -ne 0 ]; then
 
-	echo "checkconf script exited with non-zero status"
+	echo "Unable to start control panel. checkconf script exited with non-zero status"
 	failure
 	echo
 	exit $RETVAL
 
     fi
+
+# say we're starting up...
+
+    echo -n $"Starting control panel: "
 
 # check httpd version series. The result of this command will look like: 1.3 , 2.0 , etc
     httpd_v=$($httpd -v | sed '2d' | awk '{print $3}' | sed 's|.*/||' | sed 's/\./ /g' | awk '{print $1"."$2}')
@@ -89,17 +121,27 @@ start() {
 
     fi
 
+# make sure the docroot.conf file is populated
+echo "DocumentRoot $RC_ROOT/httpdocs" > $RC_ROOT/etc/docroot.conf
+
 # set our runtime options
 # conf file is different depending on the httpd version
-    OPTIONS="$OPTIONS -d $RC_ROOT -f etc/ravencore.httpd-$httpd_v.conf -C 'DocumentRoot $RC_ROOT/httpdocs'"
+    OPTIONS="$OPTIONS -d $RC_ROOT -f etc/ravencore.httpd-$httpd_v.conf"
 
-# check for the path to awstats icons
+# check for compiled-in modules, and include the ones that are not, that we need to function
 
-    awstats=$(cat $RC_ROOT/var/run/awstats_root.path 2> /dev/null)
+# get the list from the apache binary
+    compiled_modules=`$httpd -l`
 
-    if [ -d "$awstats" ]; then
-	OPTIONS="$OPTIONS -C 'Alias /icon $awstats/wwwroot/icon'"
-    fi
+    for module in log_config setenvif mime autoindex negotiation dir actions alias include; do
+
+	if [ -z "$(echo $compiled_modules | grep $module)" ]; then
+
+	    OPTIONS="$OPTIONS -D$module"
+
+	fi
+
+    done
 
 # check to make sure our httpd_modules symlink is correct
 
@@ -121,7 +163,8 @@ start() {
 # can't find the httpd modules directory. exit with error
 
 	    echo "Unable to determine the path to the httpd modules"
-
+	    failure
+	    echo
 	    exit 1
 
 	fi
@@ -131,15 +174,21 @@ start() {
 # only load PHP if we have it installed. If it isn't installed, our no_php.html will show up as the
 # default index page of the control panel
 
-# we use the wildcard here because it can be either libphp4.so or libphp5.so. Haven't tested the
-# control panel with php5 yet, but might as well assume that it does until proven otherwise.
+# php5 listed first, because on a test system with both php5 and php4 libs installed, mysql only worked with
+# php5 loaded
     
-    if [ -x $RC_ROOT/etc/httpd_modules/libphp*.so ]; then
+    if [ -f $RC_ROOT/etc/httpd_modules/libphp5.so ]; then
 	
-	OPTIONS="$OPTIONS -DPHP"
+	OPTIONS="$OPTIONS -DPHP5"
 	
+    elif [ -f $RC_ROOT/etc/httpd_modules/libphp4.so ]; then
+
+        OPTIONS="$OPTIONS -DPHP4"
+
     else
-	
+
+# couldn't find php. Obviously a bad thing :)
+
 	echo -n " (no php)"
 	
     fi
@@ -197,17 +246,34 @@ start() {
     fi
 
 # unset these enviroment variables so they don't get set in the apache enviroment
-# we want to keep AWSTATS_ROOT exported, though, because we use that one in 
-# the webstats.php page
     
     export INIT_RUNNING= GOT_CONF=
     
 # start the control panel daemon
-    
+
+if [ $found_init_func -eq 1 ]; then
+
     daemon $httpd $OPTIONS
     RETVAL=$?
     echo
     [ $RETVAL = 0 ] && touch ${lockfile}
+
+else
+
+    $httpd $OPTIONS
+    RETVAL=$?
+
+    if [ $RETVAL -eq 0 ]; then
+
+	echo "[ OK ]"
+
+    else
+
+	echo "[ FAILED ]"
+
+    fi
+
+fi
     
     return $RETVAL
     
@@ -215,11 +281,31 @@ start() {
 
 stop() {
 
-	echo -n $"Stopping control panel: "
+    echo -n $"Stopping control panel: "
+
+    if [ $found_init_func -eq 1 ]; then
+
 	killproc $httpd
 	RETVAL=$?
 	echo
 	[ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
+
+    else
+
+	killall -9 $httpd &> /dev/null
+	RETVAL=$?
+
+	if [ $RETVAL -eq 0 ]; then
+	    
+	    success
+	    
+	else
+	    
+	    failure
+	    
+	fi
+
+    fi
 
 }
 startall() {
@@ -233,11 +319,11 @@ startall() {
 	    
 	    if [ -f $RC_ROOT/conf.d/$conf ]; then
 		
-		$INITD $service status &> /dev/null
+		$INITD/$service status &> /dev/null
 	    
 		if [ $? -ne 0 ]; then
 		    
-		    $INITD $service start
+		    $INITD/$service start
 		    
 		fi
 		
@@ -264,15 +350,15 @@ stopall() {
 	    
 	    if [ -f $RC_ROOT/conf.d/$conf ]; then
 		
-		$INITD $service status &> /dev/null
+		$INITD/$service status &> /dev/null
 		
 		if [ $? -eq 0 ]; then
 		    
-		    $INITD $service stop
+		    $INITD/$service stop
 		    
 		else
 		    
-		    $INITD $service status
+		    $INITD/$service status
 		    
 		fi
 
@@ -299,7 +385,7 @@ statusall() {
 	    
 	    if [ -f $RC_ROOT/conf.d/$conf ]; then
 		
-		$INITD $service status
+		$INITD/$service status
 
 	    fi
 
@@ -309,7 +395,7 @@ statusall() {
 
 # status of ravencore, too
 
-    $INITD ravencore status
+    $INITD/ravencore status
 
 }
 
